### ISSUE TITLE
User customization: history days

### ISSUE THREAD

**Issue by jostrasser** [pasrom/corona-widget-at#10]
Hi!

is it possible to make the widget a little bit more customizable for the enduser... that the user can enter a value how many days in the past should be displayed? 

Or as example a number between 3 and 7 days for the history data which can be easily configured...

If you use the medium style of the widget there is enough space to display the last 5 days ;)

Thanks JO!

**Comment by pasrom** [comment]
Something like this? Now for the small widget there are displayed 3 days and and for the medium 7 per default (changeable).
![IMG_5893](https://user-images.githubusercontent.com/32713472/99155994-8e1ef500-26bd-11eb-8a24-8170c9a02ee7.jpeg)

**Comment by jostrasser** [comment]
Looks great, thanks!

Is it also possible that you center the 7-day-incidence and active cases and stretch it over the full width of the Widget? 

I think it will look better and the users are getting the possibility to enter longer names for the values. 

BR/JO!

**Comment by pasrom** [comment]
Option A:
![IMG_5896](https://user-images.githubusercontent.com/32713472/99156406-de4b8680-26c0-11eb-8f77-18a09e547190.jpeg)

or option B:
![IMG_5895](https://user-images.githubusercontent.com/32713472/99156364-a04e6280-26c0-11eb-9268-d1b3fb7111e2.jpeg)

**Comment by jostrasser** [comment]
I think "Option A" is better to read and it is possible to enter longer names without scaling the text size. 

Can you auto-center the text like on "Option B"?
