### ISSUE TITLE
Data shown are one month behind

### ISSUE THREAD

**Issue by abbanatic** [pasrom/corona-widget-at#11]
Hi,

I use your great script from Germany. The parameters are "210;302;900" (Feldkirchen in Carinthia, Sankt Pölten City and Vienna).

About 3 or 4 days ago, the widget started to display the incidence numbers from 30/31 days ago in October and not November.

Here's a screenshot taken today:

![IMG_2165](https://user-images.githubusercontent.com/15920605/99190905-a8161180-2769-11eb-86f0-b6ac53c9f894.PNG)

I use the latest version and I also tried the versions in the other branches.

Please be so kind to take a look what's going on here. iOS version is 14.3 beta 1.

Thanks and best regards,
Thomas

**Comment by pasrom** [comment]
Hello @abbanatic,

thank you for reporting this.
Luckily that's just a representation thing. Fix is on the way.

Regards
pasrom

**Comment by abbanatic** [comment]
Hi,

thanks for the very fast answer and the fix.

Now the date is being displayed correctly, but I think the incident numbers below the dates are still wrong. Today, there're 5.569 new infections today and over 7.000 yesterday.

The numbers displayed are still the same as in my screenshot posted above.

Thanks again and best regards,
Thomas

**Comment by pasrom** [comment]
Note this from https://github.com/pasrom/corona-widget-at/issues/7#issuecomment-724981143
> so i merged the data from www.sozialministerium.at with the ages-Dashboard to get the new daily cases. As I heard, the data from www.sozialministerium.at are less accurate than the ages-Dashboard. For now I take the data from ages-Dashboard and if there are missing data for example today, it gets filled up with the data from www.sozialministerium.at.

So the incident and active cases are taken from the ages-Dashboard. The ages-Dashboard is updated every day at 14:00 for the day before (14.11). I don't know where to get the detailed data for today (15.11). With detailed data i mean the incidence and active cases of the districts.
