### ISSUE TITLE
Aktive Fälle für den aktuellen Standort anzeigen

### ISSUE THREAD

**Issue by pasrom** [pasrom/corona-widget-at#2]
Wäre es evtl. möglich unterhalb von den aktiven Fällen Österreich die aktuellen/active Coronafälle an dem aktuell befindlichen Standort anzeigen zu lassen (inkl. Ortsangabe evtl.)?
gewünscht von @herzdrache

**Comment by pasrom** [comment]
@herzdrache hast Du dir es ca. so vorgestellt:
![IMG_5832](https://user-images.githubusercontent.com/32713472/98444284-15de8f80-2111-11eb-8778-7a429d8c777d.jpeg)

**Comment by herzdrache** [comment]
Ja genau so 👍
