### ISSUE TITLE
BKZ for Wien is wrong

### ISSUE THREAD

**Issue by Gru80** [pasrom/corona-widget-at#25]
Hi, 
great widget, thanks for your work!

I just figured out the the BKZ for `Wien` in the [json data](https://api.npoint.io/8163b3aacafa8e541609) (`jsonBKZData = "https://api.npoint.io/8163b3aacafa8e541609"`) is `901` - however in `CovidFaelle_Timeline_GKZ.csv` of the [ages.at website](https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline_GKZ.csv) `Wien` has `900`, so for Vienna-based folks showing the  location-based numbers is not working

**Comment by pasrom** [comment]
Hi @Gru80,

thank you for submitting this bug report and pointing me to the failure. Can you please test [this](https://github.com/pasrom/corona-widget-at/blob/fix-25/incidence_at.js) updated script?

**Comment by pasrom** [comment]
I think it's no fixed, the API I'm using to get reverse geolocation (location to BKZ) isn't as robust as I was hoping.
Have to search for an alternative.

**Comment by Gru80** [comment]
Hi,

yep, the regular expression unfortunately does not work since Vienna has no "Bezirk" Prefix.
I've tried a [different approach for getting the reverse geolocation on my fork](https://github.com/Gru80/corona-widget-at/blob/c65725822621abe25712145c866da39d232dba02/incidence_at.js#L245), which seems to do a decent job

**Comment by pasrom** [comment]
thank you, I cherry picked your change and added it [here](https://github.com/pasrom/corona-widget-at/pull/26/files).
