### ISSUE TITLE
Integration of „states / Bundesländer“

### ISSUE THREAD

**Issue by jostrasser** [pasrom/corona-widget-at#4]
Hi,

Is there a way to display the stats of a state (for example "Kärnten") on the widget?

Thanks!

**Comment by pasrom** [comment]
Hello,

yes that is possible, I will look into that.

regards
Roman

**Comment by jostrasser** [comment]
Many thanks!

BR Johannes

**Comment by pasrom** [comment]
my suggestion:
![IMG_5836](https://user-images.githubusercontent.com/32713472/98451779-43472f80-2149-11eb-8011-12f829b2ee29.jpeg)

**Comment by jostrasser** [comment]
Looks great! Thanks!

How is it possible to customize the state? Will this be done automatically or can it be also done manually like the disctricts?

Thanks!

**Comment by pasrom** [comment]
An excerpt from the (updated) readme:
* If you like to specify your own disctricts or states, for example add following widget parameters: `204,KFL;312;706;8,Vbg.` for Klagenfurt Land (shown as `KFL`), Korneuburg, Landeck and the state Vorarlberg shown as `Vbg.`. The 3-digit GKZ can be found in the third row of https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline_GKZ.csv. The state ID can be found here: https://covid19-dashboard.ages.at/data/CovidFaelle_Timeline.csv.

Do you know how to pass parameters to scriptable?

**Comment by jostrasser** [comment]
Perfect thanks!
Yes, I know it...

I will test it tomorrow;)

Thanks for your fast implementation!

BR Johannes!
