### ISSUE TITLE
Possibility to get today’s data into Widget

### ISSUE THREAD

**Issue by jostrasser** [pasrom/corona-widget-at#7]
Hi,

Is it possible to get a higher refresh rate? 

The widget is displaying data from yesterday 3 days into the past. 

Is it possible to get also the latest today's data?

Thanks JO!

**Comment by pasrom** [comment]
Hello @jostrasser,

so i merged the data from [www.sozialministerium.at](https://www.sozialministerium.at/Informationen-zum-Coronavirus/Neuartiges-Coronavirus-(2019-nCov).html) with the [ages-Dashboard](https://covid19-dashboard.ages.at) to get the new daily cases. As I heard, the data from [www.sozialministerium.at](https://www.sozialministerium.at/Informationen-zum-Coronavirus/Neuartiges-Coronavirus-(2019-nCov).html) are less accurate than the [ages-Dashboard](https://covid19-dashboard.ages.at). For now I take the data from [ages-Dashboard](https://covid19-dashboard.ages.at) and if there are missing data for example today, it gets filled up with the data from [www.sozialministerium.at](https://www.sozialministerium.at/Informationen-zum-Coronavirus/Neuartiges-Coronavirus-(2019-nCov).html).
here is the preview:
![IMG_5866](https://user-images.githubusercontent.com/32713472/98735331-80a6f980-23a3-11eb-9b85-69112a69d4e7.jpeg)
I need to do a code cleanup and then I'm going to push it.

**Comment by jostrasser** [comment]
Wow! Great! Thanks a lot! :)

BR/JO!
